version: '3'

services:

  redis:
    image: redis
    command: redis-server --appendonly yes

  sixpack:
    build:
      context: .
      dockerfile: Sixpack.docker
    command: sixpack
    ports:
      - "5000:5000"

  sixpack_web:
    build:
      context: .
      dockerfile: Sixpack.docker
    command: sixpack-web
    ports:
      - "5001:5001"
